### ISSUE TITLE
+ references to US MBON Working Groups

### ISSUE THREAD

**Issue by MathewBiddle** [marinebon/www_marinebon2#50] opened 2024-02-07 15:56 UTC
On the website we should include a summary of each working group and how to get involved:

- [ ]  eDNA: environmental DNA 
- [ ] DMAC: Data Management and Cyberinfrastructure 
- [ ] Remote sensing/Seascapes 
- [ ] BioTrack
- [ ] BioSound 
- [ ] Indicators  
- [ ] Ecosystem function 
- [ ] Stakeholder engagement

**Comment by 7yl4r** [comment] 2024-02-28 13:33
duplicate of https://github.com/marinebon/marinebon_wordpress_website/issues/24

thank you for the more complete list of working groups. I am updating my table now.

**Closed by 7yl4r** 2024-02-28 13:33 UTC
